FROM public.ecr.aws/lambda/python:3.9

# Copies requirements.txt file into the container
COPY requirements.txt .

# Installs dependencies found in your requirements.txt file
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

WORKDIR ${LAMBDA_TASK_ROOT}
ADD lambda lambda/

# Set the CMD to your handler start function
CMD [ "lambda.lambda_handler.handler" ]
